
import { type Step, type Question } from '../types';

export const STEP_ONE_SEED: Step = {
  id: '1',
  program: 'NA', // Can be adapted for AA
  title: 'Step One: We admitted we were powerless over our addiction, that our lives had become unmanageable.',
  order: 1,
  sections: [
    { id: 'disease-of-addiction', title: 'Disease of Addiction', order: 1 },
    { id: 'denial-patterns', title: 'Denial Patterns', order: 2 },
    { id: 'bottom-isolation', title: 'Bottom/Isolation', order: 3 },
    { id: 'powerlessness', title: 'Powerlessness', order: 4 },
    { id: 'unmanageability', title: 'Unmanageability', order: 5 },
    { id: 'reservations', title: 'Reservations', order: 6 },
    { id: 'surrender', title: 'Surrender', order: 7 },
    { id: 'spiritual-principles', title: 'Spiritual Principles', order: 8 },
    { id: 'moving-on', title: 'Moving On', order: 9 },
  ],
};

export const STEP_ONE_QUESTIONS_SEED: Question[] = [
  {
    id: 'q1-1',
    stepId: '1',
    sectionId: 'disease-of-addiction',
    order: 1,
    prompt: "In my words, what does ‘addiction as a disease’ mean for me right now?",
    helpText: "Consider how this concept shifts your perspective from moral failing to a health issue.",
    responseType: 'longtext',
  },
  {
    id: 'q1-2',
    stepId: '1',
    sectionId: 'denial-patterns',
    order: 2,
    prompt: "Where have I minimized harm or rationalized behavior to avoid facing it?",
    helpText: "Think about specific times you made excuses for yourself or others.",
    responseType: 'longtext',
  },
  {
    id: 'q1-3',
    stepId: '1',
    sectionId: 'bottom-isolation',
    order: 3,
    prompt: "What crisis (or string of moments) nudged me toward recovery?",
    helpText: "This could be a single event or a gradual realization. Describe the feeling of being at a 'bottom'.",
    responseType: 'longtext',
  },
  {
    id: 'q1-4',
    stepId: '1',
    sectionId: 'powerlessness',
    order: 4,
    prompt: "What exactly am I powerless over? Describe specific patterns/moments.",
    helpText: "Focus on the first use/drink/act and the resulting chain of events.",
    responseType: 'longtext',
  },
  {
    id: 'q1-5',
    stepId: '1',
    sectionId: 'unmanageability',
    order: 5,
    prompt: "What outer (work/legal/relationships) and inner (beliefs/emotions) signs show unmanageability?",
    helpText: "List concrete examples for both the external chaos and the internal turmoil.",
    responseType: 'longtext',
  },
  {
    id: 'q1-6',
    stepId: '1',
    sectionId: 'reservations',
    order: 6,
    prompt: "Do I keep any ‘escape hatches’ that could set me up to relapse?",
    helpText: "A reservation is a thought like 'I can use again if...' or 'This program doesn't apply to...'. Be honest.",
    responseType: 'longtext',
  },
  {
    id: 'q1-7',
    stepId: '1',
    sectionId: 'surrender',
    order: 7,
    prompt: "What convinces me I can’t go back to ‘controlled using’? What does surrender look like today?",
    helpText: "Surrender isn't giving up; it's giving in to the reality of the first step. How does that feel?",
    responseType: 'longtext',
  },
  {
    id: 'q1-8',
    stepId: '1',
    sectionId: 'spiritual-principles',
    order: 8,
    prompt: "Which spiritual principles (honesty, willingness, acceptance) am I practicing now?",
    helpText: "How are you applying these principles, even in small ways, to your daily life?",
    responseType: 'longtext',
  },
  {
    id: 'q1-9',
    stepId: '1',
    sectionId: 'moving-on',
    order: 9,
    prompt: "What tells me I’ve done enough on Step One to start Step Two?",
    helpText: "This is about having a gut-level acceptance of this step, not about intellectual perfection.",
    responseType: 'longtext',
  },
];
